# Generated by Django 4.2.4 on 2023-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw3', '0003_alter_order_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/', upload_to='media/'),
        ),
    ]
