# Generated by Django 4.2.4 on 2023-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_2_1_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
