# Generated by Django 4.2.4 on 2023-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_product',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
