# Generated by Django 4.2.4 on 2023-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0002_order_count_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
